apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-nginx
  labels:
    type: rc
    tier: web
spec:
  template:
    metadata:
      name: nginx
      labels:
        tier: web
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 3
