apiVersion: v1
kind: Pod
metadata:
  name: test-configmap
spec:
  containers:
    - image: ubuntu
      name: test-confimap
      command:
        - bash
        - "-c"
        - 'echo "$HELLO"'
      envFrom:
        - configMapRef:
            name: my-configmap
      resources:
        limits:
          cpu: "250m"
          memory: "1Gi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
